my_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('passy.urls')),
]

passy/urls.py
from django.conf.urls import url

from passy import views


app_name = 'passy'


urlpatterns = [
    url(r'^register', views.RegisterView.as_view(), name='register'),
    url(r'^login', views.LoginView.as_view(), name='login'),
    url(r'^logout', views.LogoutView.as_view(), name='logout'),
    url(r'^passwords/(?P<pk>[0-9]+)', views.PasswordView.as_view(), name='password'),
    url(r'^passwords/get_random', views.GetRandomPasswordView.as_view(), name='get_random_password'),
    url(r'^passwords', views.PasswordListView.as_view(), name='password_list'),
    url(r'^$', views.IndexView.as_view(), name='index'),
]

passy/models.py
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.contrib.auth.models import User

from typing import List, Dict, Any, Optional

from django.shortcuts import get_object_or_404

from passy.helpers import crypto


# Django makes us specify the max_length of CharField's, we chose to use a value that will work on all databases and should be enough
# for all our usages:
MAX_CHAR_FIELD = 255


class StoredPassword(models.Model):

    site: str = models.CharField(max_length=MAX_CHAR_FIELD)

    data: bytes = models.BinaryField()
    salt: bytes = models.BinaryField()

    owner: User = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.site

    def set(self, password: str, master_password: str) -> None:

        self.salt = crypto.generate_salt()
        crypter = crypto.get_crypter(master_password=master_password, salt=self.salt)
        self.data = crypter.encrypt(password.encode())

    def get(self, master_password: str) -> str:

        crypter = crypto.get_crypter(master_password=master_password, salt=self.salt)

        password = crypter.decrypt(self.data).decode()

        return password


def get_passwords(**kwargs: Dict[str, Any]) -> List[StoredPassword]:
    return StoredPassword.objects.filter(**kwargs)


def get_password(**kwargs: Dict[str, Any]) -> StoredPassword:
    return get_object_or_404(StoredPassword, **kwargs)


def get_user_or_none(**kwargs: Dict[str, Any]) -> Optional[User]:

    try:
        return User.objects.get(**kwargs)
    except ObjectDoesNotExist:
        return None

passy/forms.py
import json

from passy import models
from passy.helpers import crypto
from passy.helpers import typing

from passy_forms.forms.fields import CharField, EmailField, PasswordField, IntegerField, BooleanField, TextPasswordField
from passy_forms.forms.forms import Form


class StoredPassword(Form):

    site = CharField(label="Site or application name:")
    stored_password_text = TextPasswordField(label="New password:")

    @classmethod
    def from_request_and_instance(cls, request: typing.Request, instance: models.StoredPassword) -> "StoredPassword":

        request_data = json.loads(request.body) if request.body else dict()

        site = request_data.get("site") or instance.site
        stored_password_text = request_data.get("stored_password_text") or instance.get(master_password=request.session['master_password'])

        final_data = dict(site=site, stored_password_text=stored_password_text)

        return cls(data=final_data)

    def create_model(self, request: typing.Request) -> bool:

        instance = models.StoredPassword()

        return self.update_model(request, instance, check_for_existing_user=True)

    def update_model(self, request: typing.Request, instance: models.StoredPassword, check_for_existing_user: bool = False) -> bool:

        if not self.is_valid():
            return False

        instance.site = self.get_value('site')
        instance.owner = request.user

        instance.set(self.get_value('stored_password_text'), request.session['master_password'])

        if check_for_existing_user and models.StoredPassword.objects.filter(owner=request.user, site=instance.site).exists():
            self.add_error(field='site', error=f"This name {instance.site} is already used for another password")
            return False
        else:
            instance.save()

        return True


class GeneratedPasswordRequest(Form):

    length = IntegerField(initial=crypto.default_password_length)
    use_symbols = BooleanField(initial=True)

    def get_random_password(self) -> str:
        return crypto.generate_random_password(length=self.get_value('length'), use_symbols=self.get_value('use_symbols'))


class Login(Form):

    username = CharField(max_length=models.MAX_CHAR_FIELD, label="User Name:")
    master_password = PasswordField(label="Password:")


class Register(Form):

    email = EmailField(label="Email:", disabled=True)

    username = CharField(max_length=models.MAX_CHAR_FIELD, label="User Name:")

    password = PasswordField(label="Password:")
    repeated_password = PasswordField(label="Confirm password:")

passy/views.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View

from passy import forms
from passy import models

from passy.helpers import shortcuts
from passy.helpers import status
from passy.helpers import typing


class IndexView(View):

    template_name = 'passy/index.html'

    def get(self, request: typing.Request) -> HttpResponse:
        return render(request, self.template_name, dict())


class RegisterView(View):

    template_name = 'passy/register.html'

    def get(self, request: typing.Request) -> HttpResponse:
        return self.finalize_result(request, forms.Register())

    def post(self, request: typing.Request) -> HttpResponse:
        return self.finalize_result(request, forms.Register())

    def finalize_result(self, request: typing.Request, form: forms.Register) -> HttpResponse:
        return render(request, self.template_name, dict(form=form))


class LoginView(View):

    template_name = 'passy/login.html'

    def get(self, request: typing.Request) -> HttpResponse:

        return self.finalize_result(request, forms.Login())

    def post(self, request: typing.Request) -> HttpResponse:

        form = forms.Login(data=request.POST)

        if form.is_valid():

            username = form.cleaned_data['username']
            master_password = form.cleaned_data['master_password']

            user = auth.authenticate(username=username, password=master_password)
            if user is not None:

                auth.login(request, user)
                request.session['master_password'] = master_password
                return shortcuts.redirect('passy:password_list')

            user = models.get_user_or_none(username=username)
            if user is not None:
                if not user.is_active:
                    form.add_error(field=None, error=f"The user '{username}' is not activated yet")
                else:
                    form.add_error(field="master_password", error="Incorrect password")
            else:
                form.add_error(field="username", error="Incorrect username")

        return self.finalize_result(request, form)

    def finalize_result(self, request: typing.Request, form: forms.Login) -> HttpResponse:

        return render(request, self.template_name, dict(form=form))


class LogoutView(View):

    @staticmethod
    def post(request: typing.Request) -> HttpResponse:

        auth.logout(request)

        return shortcuts.redirect('passy:index')


@method_decorator(login_required, name='dispatch')
class PasswordListView(View):

    template_name = 'passy/password_list.html'

    def post(self, request: typing.Request) -> HttpResponse:

        form = forms.StoredPassword(data=request.POST)
        form.create_model(request)

        return self.finalize_result(request, form)

    def get(self, request: typing.Request) -> HttpResponse:

        return self.finalize_result(request, forms.StoredPassword())

    def finalize_result(self, request: typing.Request, form: forms.StoredPassword) -> HttpResponse:

        generated_password_request_form = forms.GeneratedPasswordRequest()

        data = dict(stored_passwords=models.get_passwords(owner=request.user),
                    password_form=form,
                    generated_password_request_form=generated_password_request_form)

        return render(request, self.template_name, data)


@method_decorator(login_required, name='dispatch')
class PasswordView(View):

    template_name = 'passy/password.html'

    @staticmethod
    def get_object(request: typing.Request, pk: str) -> models.StoredPassword:
        return models.get_password(owner=request.user, pk=int(pk))

    def patch(self, request: typing.Request, pk: str) -> HttpResponse:

        instance = self.get_object(request, pk)

        form = forms.StoredPassword.from_request_and_instance(request=request, instance=instance)

        if form.update_model(request, instance):
            return shortcuts.redirect('passy:password_list')
        else:
            # todo: make sure we show the errors
            return self.finalize_result(request, instance, form)

    def get(self, request: typing.Request, pk: str) -> HttpResponse:

        instance = self.get_object(request, pk)

        form = forms.StoredPassword.from_request_and_instance(request=request, instance=instance)

        if request.is_ajax():
            return JsonResponse(data=form.to_dict(), status=status.HTTP_200_OK)
        else:
            return self.finalize_result(request, instance, form)

    def delete(self, request: typing.Request, pk: str) -> HttpResponse:

        instance = self.get_object(request, pk)

        instance.delete()

        return shortcuts.redirect('passy:password_list')

    def finalize_result(self, request: typing.Request, instance: models.StoredPassword, form: forms.StoredPassword) -> HttpResponse:

        generated_password_request_form = forms.GeneratedPasswordRequest()

        data = dict(pk=instance.pk, password_form=form, generated_password_request_form=generated_password_request_form)

        return render(request, self.template_name, data)


@method_decorator(login_required, name='dispatch')
class GetRandomPasswordView(View):

    @staticmethod
    def get(request: typing.Request) -> HttpResponse:

        form = forms.GeneratedPasswordRequest(data=request.GET)
        if form.is_valid():
            return JsonResponse(data=dict(generated_password=form.get_random_password()), status=status.HTTP_200_OK)
        else:
            return JsonResponse(data=form.errors, status=status.HTTP_400_BAD_REQUEST)

passy/templates/passy/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Passy - {{ request.resolver_match.url_name }}</title>
        <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" />
        <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap-theme.min.css' %}" />
        {% block head_scripts %}
            <script src="{% static "jquery/dist/jquery.min.js" %}"></script>
            <script src="{% static "bootstrap/dist/js//bootstrap.min.js" %}"></script>
            <script src="{% static "js-cookie/src/js.cookie.js" %}"></script>
            <script src="{% static "passy/ajax-form.js" %}"></script>
        {% endblock head_scripts %}
    </head>

    <body>
        <header class="navbar navbar-default" id="top">
            <div class="container">
                <div class="navbar-header">
                    <a href="{% url 'passy:index' %}" class="navbar-brand">Passy</a>
                </div>
                <nav class="collapse navbar-collapse" id="bs-navbar">
                    <ul class="nav navbar-nav">
                        {% if request.user.is_authenticated %}
                            <li><a href="{% url 'passy:password_list' %}">passwords</a></li>
                        {% else %}
                            <li><a href="{% url 'passy:register' %}">register</a></li>
                        {% endif %}
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if request.user.is_authenticated %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a onclick="document.getElementById('hidden_logout_form_button').click()">logout</a></li>
                            </ul>
                        </li>
                        {% else %}
                            <li><a href="{% url 'passy:login' %}">login</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
            <form action="{% url 'passy:logout' %}" method="post">
                {% csrf_token %}
                <input id="hidden_logout_form_button" class="btn dropdown-item" type="submit" value="Logout" style="visibility:hidden;display:none">
            </form>
        </header>

        <div class="container">
            <div class="col-md-9" role="main">
                {% if form %}{% include "passy_forms/forms/render/error.html" with errors=field.non_field_errors %}{% endif %}
                {% block content %}
                {% endblock content %}
            </div>
        </div>
        {% block footer_scripts %}
        {% endblock footer_scripts %}
    </body>
</html>

passy/templates/passy/base_password.html
{% extends "passy/base.html" %}

{% load static %}

{% block head_scripts %}
    {{ block.super }}
    <script src="{% static "clipboard/dist/clipboard.min.js" %}"></script>
    <script src="{% static "passy/password.js" %}"></script>
{% endblock head_scripts%}

{% block content %}

    {% block start_content %}
    {% endblock start_content %}

    {% block base_form %}
        <form action="{% block form_url %}{% endblock form_url %}" method="post">
            {% csrf_token %}

            {% include 'passy_forms/forms/render/form.html' with form=password_form %}

            {% block form_hidden_buttons %}
            {% endblock form_hidden_buttons %}
        </form>
        <div class="collapse" id="collapse_get_random_password_form">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form id="get_random_password_form" action="{% url 'passy:get_random_password' %}">
                        {% include 'passy_forms/forms/render/form.html' with form=generated_password_request_form %}

                        <input id="hidden_get_another_password_button" type="submit" style="visibility:hidden;display:none">
                    </form>
                </div>
            </div>
        </div>
        {% block form_buttons %}
        {% endblock form_buttons %}
    {% endblock base_form %}

    {% block footer_scripts %}
        <script>initClipboard()</script>
        <script>initGetRandomPasswordForm()</script>
    {% endblock footer_scripts %}
{% endblock content %}

passy/templates/passy/index.html
{% extends "passy/base.html" %}

{% block content %}
    <h1>Welcome to Passy.</h1>
{% endblock content %}

passy/templates/passy/login.html
{% extends "passy/base.html" %}

{% block content %}
    {% if request.user.is_authenticated %}
        <h1>You are already logged in!</h1>
    {% else %}
        <form action="{% url 'passy:login' %}" method="post">
            {% csrf_token %}
            {% include 'passy_forms/forms/render/form.html' with form=form %}
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    {% endif %}
{% endblock content %}

passy/templates/passy/password.html
{% extends "passy/base_password.html" %}

{% block form_url %}{% url 'passy:password' pk %}{% endblock form_url %}

{% block form_hidden_buttons %}
    <input id="hidden_patch_button" type="submit" value="" data-method="patch" style="visibility:hidden;display:none">
    <input id="hidden_delete_button" type="submit" value="" data-method="delete" style="visibility:hidden;display:none">
{% endblock form_hidden_buttons %}

{% block form_buttons %}
    {{ block.super }}
    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#confirm_dialog">Delete</button>
    <input class="btn btn-primary" type="button" value="Change" id="hidden_clipboard_change"
           data-clipboard-target="#{{ password_form.stored_password_text.id_for_label  }}"
           data-execute-target="hidden_patch_button" />
    <div class="modal fade" id="confirm_dialog" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Are you sure you want to delete this password?</h4>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" onclick="document.getElementById('hidden_delete_button').click()">Yes</button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
                </div>
            </div>
        </div>
    </div>
{% endblock form_buttons %}

passy/templates/passy/password_list.html
{% extends "passy/base_password.html" %}

{% block start_content %}

    <h3>The list of stored passwords:</h3>

    <input name="filter" id="filter" class="form-control" type="text" placeholder="Filter.." oninput="filterPage(this.value)">
    {% if stored_passwords %}
        <table id="passwords_table" class="table table-hover">
            <thead>
                <tr>
                    <th>Site</th>
                    <th class="text-right">Password</th>
                </tr>
            </thead>
            <tbody>
                {% for password in stored_passwords %}
                    <tr>
                        <td>
                            <a name="site_link" href="{% url 'passy:password' password.pk %}">{{ password.site }}</a>
                        </td>
                        <td class="text-right">
                            <button id="download_{{ forloop.counter }}" type="button" class="btn btn-default"
                                    onclick='fillPassword("{% url 'passy:password' password.pk %}", "{{ forloop.counter }}")'>
                                <span class="glyphicon glyphicon-download"></span>
                            </button>

                            <button id="clipboard_{{ forloop.counter }}"
                                    class="btn btn-default"
                                    style="visibility:hidden;display:none"
                                    data-clipboard-text="empty">
                                <span class="glyphicon glyphicon glyphicon-copy"></span>
                            </button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No passwords are stored yet!</p>
    {% endif %}

    <h3>Add another:</h3>
{% endblock start_content %}

{% block form_url %}{% url 'passy:password_list' %}{% endblock form_url %}

{% block form_hidden_buttons %}
    <input class="btn btn-default" id="hidden_post_button" type="submit" value="" data-method="post" style="visibility:hidden;display:none">
{% endblock form_hidden_buttons %}

{% block form_buttons %}
    {{ block.super }}
    <input class="btn btn-primary" type="button" value="Save the password" id="hidden_clipboard_save"
           data-clipboard-target="#{{ password_form.stored_password_text.id_for_label  }}"
           data-execute-target="hidden_post_button" />
{% endblock form_buttons %}

passy/templates/passy/register.html
{% extends "passy/base.html" %}

{% block content %}
    {% if request.user.is_authenticated %}
        <h1>You are already registered and logged in!</h1>
    {% else %}
        <form action="{% url 'passy:register' %}" method="post">
            {% csrf_token %}
            {% include 'passy_forms/forms/render/form.html' with form=form %}
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
    {% endif %}
{% endblock content %}